#!/bin/sh

# wal -i /home/laughing/Pictures/DT/0026.jpg > /dev/null &
# setbg /home/laughing/Pictures/DT/0223.jpg &
# setbg  &
# wp-autochange ~/Pictures/ 2m &
setbg-time  &
wp-autochange-time 2m &
mpd &

picom -b &
unclutter &		# Remove mouse when idle

fcitx &
dunst &

select_screen HDMI-1-0 && xrandr --output HDMI-1-0 --mode 2560x1440 --rate 144
